workspace(name = "test_rules_terraform")

local_repository(
    name = "rules_terraform",
    path = "../",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

load(
    "@rules_terraform//:deps.bzl",
    "rules_terraform_dependencies",
)

rules_terraform_dependencies()

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains(version = "1.17.5")

# TODO: It would be nice to not need these, but there are problems recursively
# evaluating WORKSPACE files. See:
# - https://github.com/bazelbuild/bazel/issues/1550
# - https://github.com/bazelbuild/bazel/issues/1943
load("@io_bazel_rules_jsonnet//jsonnet:jsonnet.bzl", "jsonnet_repositories")
jsonnet_repositories()

# load("@jsonnet_go//bazel:repositories.bzl", "jsonnet_go_repositories")
# jsonnet_go_repositories()
# load("@jsonnet_go//bazel:deps.bzl", "jsonnet_go_dependencies")
# jsonnet_go_dependencies()

# Once we use rules_jsonnet 0.4.0:
# https://github.com/bazelbuild/rules_jsonnet/commit/fa78c32a4bc77a618eff04399db8fbe603e203fa
load("@google_jsonnet_go//bazel:repositories.bzl", "jsonnet_go_repositories")
jsonnet_go_repositories()
load("@google_jsonnet_go//bazel:deps.bzl", "jsonnet_go_dependencies")
jsonnet_go_dependencies()

http_archive(
    name = "bazel_gazelle",
    sha256 = "de69a09dc70417580aabf20a28619bb3ef60d038470c7cf8442fafcf627c21cb",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.24.0/bazel-gazelle-v0.24.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.24.0/bazel-gazelle-v0.24.0.tar.gz",
    ],
)

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")

load(
    "@rules_terraform//:defs.bzl",
    "download_terraform_versions",
    "download_terraform_provider_versions",
)

download_terraform_versions({
    # These are SHAs of the SHA265SUM file for a given version. They can be
    # found with:
    # curl https://releases.hashicorp.com/terraform/{version}/terraform_{version}_SHA256SUMS | sha256sum
    "0.12.31": "f9a95c24c77091a1ae0ca2539f39ccfb2639c59934858fada6f4950541386fad",
    "1.1.2": "20e4115a8c6aff07421ebc6645056f9a6605ab5a196475ab46a65fea71b6b090",
})

# Provider SHAs are from the SHA265SUM file for a given version. They can be
# found with:
# curl https://releases.hashicorp.com/terraform-provider-{name}/{version}/terraform-provider-{name}_{version}_SHA256SUMS | sha256sum
download_terraform_provider_versions(
    "aws",
    "registry.terraform.io/hashicorp/aws",
    {
        "3.67.0": "28a434313ee86d8ed2721360e5741957bcc48b1a102d878f0fb34274f41aee81",
    },
)

download_terraform_provider_versions(
    "local",
    "registry.terraform.io/hashicorp/local",
    {
        "2.1.0": "dae594d82be6be5ee83f8d081cc8a05af45ac1bbf7fdb8bea16ab4c1d6032043",
    },
)

download_terraform_provider_versions(
    "time",
    "registry.terraform.io/hashicorp/time",
    {
        "0.7.0": "ccd73836657ce361f83a5f11f0359cd366f2a228a0c03c78db11baf47c5a2d94",
    },
)
