workspace(name = "test_rules_terraform")

# rules_terraform
local_repository(
    name = "rules_terraform",
    path = "../",
)

load("@rules_terraform//:deps.bzl", "rules_terraform_repositories")
rules_terraform_repositories()

load(
    "@rules_terraform//:defs.bzl",
    "download_terraform_versions",
    "download_terraform_provider_versions",
)

download_terraform_versions({
    # These are SHAs of the SHA265SUM file for a given version. They can be
    # found with:
    # curl https://releases.hashicorp.com/terraform/{version}/terraform_{version}_SHA256SUMS | sha256sum
    "0.12.31": "f9a95c24c77091a1ae0ca2539f39ccfb2639c59934858fada6f4950541386fad",
    "1.1.2": "20e4115a8c6aff07421ebc6645056f9a6605ab5a196475ab46a65fea71b6b090",
})

# Provider SHAs are from the SHA265SUM file for a given version. They can be
# found with:
# curl https://releases.hashicorp.com/terraform-provider-{name}/{version}/terraform-provider-{name}_{version}_SHA256SUMS | sha256sum
download_terraform_provider_versions(
    "aws",
    "registry.terraform.io/hashicorp/aws",
    {
        "3.67.0": "28a434313ee86d8ed2721360e5741957bcc48b1a102d878f0fb34274f41aee81",
    },
)

download_terraform_provider_versions(
    "local",
    "registry.terraform.io/hashicorp/local",
    {
        "2.1.0": "dae594d82be6be5ee83f8d081cc8a05af45ac1bbf7fdb8bea16ab4c1d6032043",
    },
)

download_terraform_provider_versions(
    "time",
    "registry.terraform.io/hashicorp/time",
    {
        "0.7.0": "ccd73836657ce361f83a5f11f0359cd366f2a228a0c03c78db11baf47c5a2d94",
    },
)

#
# Go dependencies for rules_terraform
#
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "2b1641428dff9018f9e85c0384f03ec6c10660d935b750e3fa1492a281a53b0f",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.29.0/rules_go-v0.29.0.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.29.0/rules_go-v0.29.0.zip",
    ],
)

http_archive(
    name = "bazel_gazelle",
    sha256 = "de69a09dc70417580aabf20a28619bb3ef60d038470c7cf8442fafcf627c21cb",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.24.0/bazel-gazelle-v0.24.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.24.0/bazel-gazelle-v0.24.0.tar.gz",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")

go_rules_dependencies()

# On NixOS, need to use host toolchain
# https://github.com/bazelbuild/rules_go/issues/1376
go_register_toolchains(version = "host")
# go_register_toolchains(version = "1.17.1")

gazelle_dependencies()
